---
abstract: 'log statistics for your Dezi server'
author:
  - 'Peter Karman, C<< <karman at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: http://dev.perl.org/licenses/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dezi-Stats
no_index:
  directory:
    - inc
    - t
recommends:
  DBIx::Connector: 0
  DBIx::InsertHash: 0
  Log::Dispatchouli: 0
requires:
  Dezi: 0.002007
  Module::Load: 0
  Search::OpenSearch::Server: 0.15
  Test::More: 0
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dezi-Stats
  homepage: https://github.com/karpet/dezi-stats
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/karpet/dezi-stats
version: 0.001006
